#!/usr/bin/env bash
# ############################################################################
# syncAnsibleRoles
#
# Description: Queries a GIT Group and clones/pulls all projects into the
#     /opt/ansible/roles directory.
#
#     Originally started with this file is copied into /etc/cron.hourly but due
#     to authentication with Git switched to adding the following entry to
#     /etc/crontab to check every 30 minutes.
#       0,30 * * * * m86014 /opt/AnsibleProjects/git-scripts/syncAnsibleRoles
#
# ----------------------------------------------------------------------------
# LOG FILES:
#       Cron LOG: /var/log/cron
#     Script LOG: $LOG_DIR/syncAnsibleRoles
#
# Restarting cron on RHEL6
#    - sudo service crond stop
#    - sudo service crond start
#
# ChangeLog:
#   - 2018-08-17 - Kevin Kehres (a57203)
#     - Updated to use GitLab v4 API as v3 was disabled after GitLab upgrade
#     - Comment out syncing roles from Galaxy since they are not useful
#
#   - 2018-01-20: Kevin Kehres (a57203)
#      - add if to check if TARGET_DIR exists and create it if it doesn't
#      - remove logging
#      - change umask so everyone can't change files
#
#   - 2017-02-28: Gordon Dickens (m86014)
#     - Performing a git reset before pulling
#     - Removed GitLab_Private_Token, must be set in Environment Variable by user
#
#   - 2016-11-01 - Gordon Dickens (m86014)
#     - Initial Release
#
# ----------------------------------------------------------------------------
# NOTE: this script requires "jq" be installed: sudo yum -y install jq
# GitLab Documentation: https://docs.gitlab.com/ce/api/projects.html#list-projects
# ############################################################################
umask 002

BASE_PATH="http://git.sys.cigna.com/"
PROJECT_SEARCH_PARAM="*"
LOG_FILE="/dev/null"
FILENAME="repos.json"
TARGET_DIR=/opt/ansible/roles

if [ ! -d $TARGET_DIR ]; then
  mkdir $TARGET_DIR;
fi

cd $TARGET_DIR;

function log {
  echo $(date +"%m-%d-%Y %H:%M") - $1
}

function fetch {
    log "about to Curl...${BASE_PATH}api/v4/groups/$1/projects?private_token=$GITLAB_PRIVATE_TOKEN"


    curl -s "${BASE_PATH}api/v4/groups/$1/projects?private_token=$GITLAB_PRIVATE_TOKEN" \
        | jq --raw-output --compact-output ".[] | select(.namespace.name == \"$1\") | { "path": .path, "git": .ssh_url_to_repo }" > "$FILENAME"

    while read repo; do
        THEPATH=$(echo "$repo" | jq -r ".path")
        log "YOUR PATH: $THEPATH"
        GIT=$(echo "$repo" | jq -r ".git")
        log "YOUR REPO: $GIT"

        if [ ! -d "$THEPATH" ]; then
            log "Cloning $THEPATH ( $GIT )"
            /usr/bin/git clone "$GIT" --quiet
        else
            log "Pulling $THEPATH"
            (cd "$THEPATH" && /usr/bin/git reset --hard && /usr/bin/git pull --quiet)
        fi
    done < "$FILENAME"

    log "--- Repositories Processed ---"
    cat "$FILENAME"
}

if [ -z "$GITLAB_PRIVATE_TOKEN" ]; then
    log "Please set the environment variable GITLAB_PRIVATE_TOKEN"
    log "See ${BASE_PATH}profile/account"
    exit 1
fi

pushd $TARGET_DIR

# ############################################################################
# Enter the name of the repository groups to fetch roles from
# ############################################################################
(
    log "------------- START -------------"
    fetch "Group-IT-Galaxy"
    #fetch "Galaxy"
    log "-------------- END --------------"
) 2>&1 | tee -a "$LOG_FILE";

rm "$FILENAME"
popd
